name: Test pull request

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

concurrency:
  group: test-pull-request
  cancel-in-progress: true

jobs:
  test-pull-request-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Regenerate node_modules from cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-install-${{ hashFiles('**/bun.lockb') }}

      - name: Install project dependencies
        run: bun install --immutable

      - name: Run templates testing
        run: bun run templates test
