name: Weekly automation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

concurrency:
  group: weekly-automation
  cancel-in-progress: true

jobs:
  weekly-automation-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Regenerate node_modules from cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-install-${{ hashFiles('**/bun.lockb') }}

      - name: Install project dependencies
        run: bun install --immutable

      - name: run templates updater
        run: bun run --cwd packages/automation templates generate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch-suffix: short-commit-hash
          commit-message: Update templates
          committer: weekly-automation-workflow<sfrady20@gmail.com>
          delete-branch: true
          token: ${{ secrets.PAT }}
